/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as ActivitesRouteImport } from './routes/activites'
import { Route as AssistanceVisaRouteImport } from './routes/assistance-visa'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as SecteursRouteImport } from './routes/secteurs'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as PolitiqueConfidentialiteRouteImport } from './routes/politique-confidentialite'
import { Route as ConditionsUtilisationRouteImport } from './routes/conditions-utilisation'
import { Route as CatalogueIndexRouteImport } from './routes/catalogue.index'
import { Route as CatalogueSlugRouteImport } from './routes/catalogue.$slug'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const AProposRoute = AProposRouteImport.update({ id: '/a-propos', path: '/a-propos', getParentRoute: () => rootRouteImport } as any)
const ActivitesRoute = ActivitesRouteImport.update({ id: '/activites', path: '/activites', getParentRoute: () => rootRouteImport } as any)
const AssistanceVisaRoute = AssistanceVisaRouteImport.update({ id: '/assistance-visa', path: '/assistance-visa', getParentRoute: () => rootRouteImport } as any)
const ContactRoute = ContactRouteImport.update({ id: '/contact', path: '/contact', getParentRoute: () => rootRouteImport } as any)
const SecteursRoute = SecteursRouteImport.update({ id: '/secteurs', path: '/secteurs', getParentRoute: () => rootRouteImport } as any)
const ServicesRoute = ServicesRouteImport.update({ id: '/services', path: '/services', getParentRoute: () => rootRouteImport } as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({ id: '/mentions-legales', path: '/mentions-legales', getParentRoute: () => rootRouteImport } as any)
const PolitiqueConfidentialiteRoute = PolitiqueConfidentialiteRouteImport.update({ id: '/politique-confidentialite', path: '/politique-confidentialite', getParentRoute: () => rootRouteImport } as any)
const ConditionsUtilisationRoute = ConditionsUtilisationRouteImport.update({ id: '/conditions-utilisation', path: '/conditions-utilisation', getParentRoute: () => rootRouteImport } as any)
const CatalogueIndexRoute = CatalogueIndexRouteImport.update({ id: '/catalogue/', path: '/catalogue/', getParentRoute: () => rootRouteImport } as any)
const CatalogueSlugRoute = CatalogueSlugRouteImport.update({ id: '/catalogue/$slug', path: '/catalogue/$slug', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/activites': typeof ActivitesRoute
  '/assistance-visa': typeof AssistanceVisaRoute
  '/contact': typeof ContactRoute
  '/secteurs': typeof SecteursRoute
  '/services': typeof ServicesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/conditions-utilisation': typeof ConditionsUtilisationRoute
  '/catalogue/': typeof CatalogueIndexRoute
  '/catalogue/$slug': typeof CatalogueSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/activites': typeof ActivitesRoute
  '/assistance-visa': typeof AssistanceVisaRoute
  '/contact': typeof ContactRoute
  '/secteurs': typeof SecteursRoute
  '/services': typeof ServicesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/conditions-utilisation': typeof ConditionsUtilisationRoute
  '/catalogue': typeof CatalogueIndexRoute
  '/catalogue/$slug': typeof CatalogueSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/activites': typeof ActivitesRoute
  '/assistance-visa': typeof AssistanceVisaRoute
  '/contact': typeof ContactRoute
  '/secteurs': typeof SecteursRoute
  '/services': typeof ServicesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/conditions-utilisation': typeof ConditionsUtilisationRoute
  '/catalogue/': typeof CatalogueIndexRoute
  '/catalogue/$slug': typeof CatalogueSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/a-propos' | '/activites' | '/assistance-visa' | '/contact' | '/secteurs' | '/services' | '/mentions-legales' | '/politique-confidentialite' | '/conditions-utilisation' | '/catalogue/' | '/catalogue/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/a-propos' | '/activites' | '/assistance-visa' | '/contact' | '/secteurs' | '/services' | '/mentions-legales' | '/politique-confidentialite' | '/conditions-utilisation' | '/catalogue' | '/catalogue/$slug'
  id: '__root__' | '/' | '/a-propos' | '/activites' | '/assistance-visa' | '/contact' | '/secteurs' | '/services' | '/mentions-legales' | '/politique-confidentialite' | '/conditions-utilisation' | '/catalogue/' | '/catalogue/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ActivitesRoute: typeof ActivitesRoute
  AssistanceVisaRoute: typeof AssistanceVisaRoute
  ContactRoute: typeof ContactRoute
  SecteursRoute: typeof SecteursRoute
  ServicesRoute: typeof ServicesRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PolitiqueConfidentialiteRoute: typeof PolitiqueConfidentialiteRoute
  ConditionsUtilisationRoute: typeof ConditionsUtilisationRoute
  CatalogueIndexRoute: typeof CatalogueIndexRoute
  CatalogueSlugRoute: typeof CatalogueSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/a-propos': { id: '/a-propos'; path: '/a-propos'; fullPath: '/a-propos'; preLoaderRoute: typeof AProposRouteImport; parentRoute: typeof rootRouteImport }
    '/activites': { id: '/activites'; path: '/activites'; fullPath: '/activites'; preLoaderRoute: typeof ActivitesRouteImport; parentRoute: typeof rootRouteImport }
    '/assistance-visa': { id: '/assistance-visa'; path: '/assistance-visa'; fullPath: '/assistance-visa'; preLoaderRoute: typeof AssistanceVisaRouteImport; parentRoute: typeof rootRouteImport }
    '/contact': { id: '/contact'; path: '/contact'; fullPath: '/contact'; preLoaderRoute: typeof ContactRouteImport; parentRoute: typeof rootRouteImport }
    '/secteurs': { id: '/secteurs'; path: '/secteurs'; fullPath: '/secteurs'; preLoaderRoute: typeof SecteursRouteImport; parentRoute: typeof rootRouteImport }
    '/services': { id: '/services'; path: '/services'; fullPath: '/services'; preLoaderRoute: typeof ServicesRouteImport; parentRoute: typeof rootRouteImport }
    '/mentions-legales': { id: '/mentions-legales'; path: '/mentions-legales'; fullPath: '/mentions-legales'; preLoaderRoute: typeof MentionsLegalesRouteImport; parentRoute: typeof rootRouteImport }
    '/politique-confidentialite': { id: '/politique-confidentialite'; path: '/politique-confidentialite'; fullPath: '/politique-confidentialite'; preLoaderRoute: typeof PolitiqueConfidentialiteRouteImport; parentRoute: typeof rootRouteImport }
    '/conditions-utilisation': { id: '/conditions-utilisation'; path: '/conditions-utilisation'; fullPath: '/conditions-utilisation'; preLoaderRoute: typeof ConditionsUtilisationRouteImport; parentRoute: typeof rootRouteImport }
    '/catalogue/': { id: '/catalogue/'; path: '/catalogue'; fullPath: '/catalogue/'; preLoaderRoute: typeof CatalogueIndexRouteImport; parentRoute: typeof rootRouteImport }
    '/catalogue/$slug': { id: '/catalogue/$slug'; path: '/catalogue/$slug'; fullPath: '/catalogue/$slug'; preLoaderRoute: typeof CatalogueSlugRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  AProposRoute,
  ActivitesRoute,
  AssistanceVisaRoute,
  ContactRoute,
  SecteursRoute,
  ServicesRoute,
  MentionsLegalesRoute,
  PolitiqueConfidentialiteRoute,
  ConditionsUtilisationRoute,
  CatalogueIndexRoute,
  CatalogueSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
