/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AssistanceVisaRouteImport } from './routes/assistance-visa'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as SecteursRouteImport } from './routes/secteurs'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ActualitesIndexRouteImport } from './routes/actualites.index'
import { Route as ActualitesSlugRouteImport } from './routes/actualites.$slug'
import { Route as CatalogueIndexRouteImport } from './routes/catalogue.index'
import { Route as CatalogueSlugRouteImport } from './routes/catalogue.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistanceVisaRoute = AssistanceVisaRouteImport.update({
  id: '/assistance-visa',
  path: '/assistance-visa',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const SecteursRoute = SecteursRouteImport.update({
  id: '/secteurs',
  path: '/secteurs',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesIndexRoute = ActualitesIndexRouteImport.update({
  id: '/actualites/',
  path: '/actualites/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesSlugRoute = ActualitesSlugRouteImport.update({
  id: '/actualites/$slug',
  path: '/actualites/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueIndexRoute = CatalogueIndexRouteImport.update({
  id: '/catalogue/',
  path: '/catalogue/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueSlugRoute = CatalogueSlugRouteImport.update({
  id: '/catalogue/$slug',
  path: '/catalogue/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/assistance-visa': typeof AssistanceVisaRoute
  '/contact': typeof ContactRoute
  '/secteurs': typeof SecteursRoute
  '/services': typeof ServicesRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/catalogue/$slug': typeof CatalogueSlugRoute
  '/actualites/': typeof ActualitesIndexRoute
  '/catalogue/': typeof CatalogueIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/assistance-visa': typeof AssistanceVisaRoute
  '/contact': typeof ContactRoute
  '/secteurs': typeof SecteursRoute
  '/services': typeof ServicesRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/catalogue/$slug': typeof CatalogueSlugRoute
  '/actualites': typeof ActualitesIndexRoute
  '/catalogue': typeof CatalogueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/assistance-visa': typeof AssistanceVisaRoute
  '/contact': typeof ContactRoute
  '/secteurs': typeof SecteursRoute
  '/services': typeof ServicesRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/catalogue/$slug': typeof CatalogueSlugRoute
  '/actualites/': typeof ActualitesIndexRoute
  '/catalogue/': typeof CatalogueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/assistance-visa'
    | '/contact'
    | '/secteurs'
    | '/services'
    | '/actualites/$slug'
    | '/catalogue/$slug'
    | '/actualites/'
    | '/catalogue/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/assistance-visa'
    | '/contact'
    | '/secteurs'
    | '/services'
    | '/actualites/$slug'
    | '/catalogue/$slug'
    | '/actualites'
    | '/catalogue'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/assistance-visa'
    | '/contact'
    | '/secteurs'
    | '/services'
    | '/actualites/$slug'
    | '/catalogue/$slug'
    | '/actualites/'
    | '/catalogue/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AssistanceVisaRoute: typeof AssistanceVisaRoute
  ContactRoute: typeof ContactRoute
  SecteursRoute: typeof SecteursRoute
  ServicesRoute: typeof ServicesRoute
  ActualitesSlugRoute: typeof ActualitesSlugRoute
  CatalogueSlugRoute: typeof CatalogueSlugRoute
  ActualitesIndexRoute: typeof ActualitesIndexRoute
  CatalogueIndexRoute: typeof CatalogueIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistance-visa': {
      id: '/assistance-visa'
      path: '/assistance-visa'
      fullPath: '/assistance-visa'
      preLoaderRoute: typeof AssistanceVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secteurs': {
      id: '/secteurs'
      path: '/secteurs'
      fullPath: '/secteurs'
      preLoaderRoute: typeof SecteursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites/': {
      id: '/actualites/'
      path: '/actualites'
      fullPath: '/actualites/'
      preLoaderRoute: typeof ActualitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites/$slug': {
      id: '/actualites/$slug'
      path: '/actualites/$slug'
      fullPath: '/actualites/$slug'
      preLoaderRoute: typeof ActualitesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue/': {
      id: '/catalogue/'
      path: '/catalogue'
      fullPath: '/catalogue/'
      preLoaderRoute: typeof CatalogueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue/$slug': {
      id: '/catalogue/$slug'
      path: '/catalogue/$slug'
      fullPath: '/catalogue/$slug'
      preLoaderRoute: typeof CatalogueSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AssistanceVisaRoute: AssistanceVisaRoute,
  ContactRoute: ContactRoute,
  SecteursRoute: SecteursRoute,
  ServicesRoute: ServicesRoute,
  ActualitesSlugRoute: ActualitesSlugRoute,
  CatalogueSlugRoute: CatalogueSlugRoute,
  ActualitesIndexRoute: ActualitesIndexRoute,
  CatalogueIndexRoute: CatalogueIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
